name: boinc

on:
  pull_request:

permissions: {}

jobs:
  compute:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Install BOINC
      run: |
        sudo apt-get update
        sudo apt install -y boinc
    - name: Run BOINC
      run: |
        uptime
        > /tmp/gui_rpc_auth.cfg
        timeout 5m boinc --dir /tmp &
        sleep 120 && boinccmd --quit
